// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PanacealogicsSales.Entities.Migrations.RepositoryContext2Migrations
{
    [DbContext(typeof(RepositoryContext2))]
    [Migration("20210618054457_SecondUpdate")]
    partial class SecondUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PanacealogicsSales.Entities.Models.Project2", b =>
                {
                    b.Property<int>("project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("external_project_id")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("proposal")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("project_id");

                    b.ToTable("Project2");
                });
#pragma warning restore 612, 618
        }
    }
}
